name: Build and Dispatch to DevOps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clone LudexWeb3Integration into packages/
        run: |
          mkdir -p packages
          git clone https://github.com/LudexCs/LudexWeb3Integration.git packages/LudexWeb3Integration

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t gomdadi/web3gateway:latest .

      - name: Push Docker image
        run: docker push gomdadi/web3gateway:latest

      - name: Dispatch to BE_DevOps
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: LudexCS/BE_DevOps
          event-type: deploy-web3gateway